dist: bionic
language: python
python:
  - "3.7"

jobs:
  include:
    - stage: "Code analysis"
      name: "Code formatting and type checking"
      install:
        - pip install black pytype
      script:
       - pytype --keep-going alphadraughts
       - black --check alphadraughts/
    - stage: "Testing"
      name: "unit testing"
      install:
        - pip install -r travis/travis_requirements.txt
      script:
        - python -m pytest tests/unittests
        - python -m pytest tests/systemtests
